WITH src_raw_sentimentdata AS (
    SELECT
        TICKER, TITLE, SOURCE, OVERALL_SENTIMENT_SCORE, OVERALL_SENTIMENT_LABEL, RELEVANCE_SCORE, SENTIMENT_DATE, rs.INSERTED_DATE
    FROM
    FINANCE_DB.RAW_SCHEMA.RAW_SENTIMENTS rs inner join 
     finance_db.references_schema.tickers_inscope ti
     on rs.ticker=ti.tickers
)
SELECT
    TICKER, TITLE, SOURCE, OVERALL_SENTIMENT_SCORE, OVERALL_SENTIMENT_LABEL, RELEVANCE_SCORE, SENTIMENT_DATE, INSERTED_DATE
FROM
    src_raw_sentimentdata
